### PR TITLE
aksd: DeployWizard: warn when deployment exceeds namespace resource quota

### LINKED ISSUE #492: Deploy wizard: no warning when deployment exceeds namespace resource quota; Map tab fails for unscheduled pods
## Problem

When deploying to a namespace with a small ResourceQuota, two issues surface:

### 1. No pre-deploy quota validation

The deploy wizard's server-side dry-run validates the Deployment object itself but **does not catch quota violations** that occur when the ReplicaSet controller creates pods. Users deploy successfully, then discover pods stuck in `FailedCreate` with no prior warning.

**Repro steps:**
1. Create an AKS managed namespace with a small resource quota (e.g., `limits.memory=128Mi`, `requests.memory=64Mi`)
2. Import the namespace as a project
3. Deploy an app using default wizard values (`requests.memory=128Mi`, `limits.memory=512Mi`)
4. Deployment succeeds, but pods never start — RS controller reports `exceeded quota`

**Expected:** The deploy wizard should warn the user before deploying that their resource requests exceed the namespace quota.

### 2. Map tab fails for unscheduled pods

When pods can't be scheduled (e.g., due to quota exceeded), the Map tab's "Group by Node" view breaks because unscheduled pods have no `spec.nodeName`. The grouping logic in `graphGrouping.tsx` returns `undefined` for the node accessor, causing pods to silently appear as ungrouped individuals with no context about why they lack a node.

**Expected:** Unscheduled pods should be grouped under an "Unscheduled" label in the node view.

### 3. ReplicaSet shows as "Healthy" despite pod failures (related)

The `getDeploymentHealth` function only checks `availableReplicas >= replicas`. While this correctly shows "Degraded" for the quota-exceeded case, it doesn't surface **why** — no quota error message is shown. (Tracked separately, not addressed in initial fix.)

## Event log from repro

```
Events:
  Type     Reason        Age    From                   Message
  Warning  FailedCreate  7m24s  replicaset-controller  Error creating: pods "contoso-air-675c4946f8-qw6x4" is forbidden: exceeded quota: defaultresourcequota, requested: limits.memory=512Mi,requests.memory=128Mi, used: limits.memory=0,requests.memory=0, limited: limits.memory=128Mi,requests.memory=64Mi
```

### Map tab (headlamp fork)
- Changed the "Group by Node" accessor to return `'Unscheduled'` sentinel instead of `undefined` for pods without `nodeName`
- Pods without a node now appear in a visible "Unscheduled" group
- Skip K8s Node object linking for the Unscheduled group

### Deploy wizard quota warning (plugin)
- Added `checkResourceQuota()` utility that fetches namespace ResourceQuotas via the K8s API and compares requested resources against remaining quota
- Shows a non-blocking warning banner in the Deploy review step when resources would exceed quota
- Fail-open design: returns no warnings if quota fetch fails (e.g., RBAC)
- Checks `requests.cpu`, `requests.memory`, `limits.cpu`, `limits.memory`
- Accounts for replica count

### New shared utilities
- `parseCpuToMillicores()`, `parseMemoryToBytes()`, `formatCpu()`, `formatMemory()` in `utils/shared/resourceUnits.ts`

## Files changed

| File | Change |
|------|--------|
| `headlamp/.../graphGrouping.tsx` | Return `'Unscheduled'` sentinel for pods without nodeName |
| `headlamp/.../graphGrouping.test.ts` | Updated + new test for Unscheduled group |
| `plugins/.../utils/quotaCheck.ts` | **New** — quota check logic |
| `plugins/.../utils/quotaCheck.test.ts` | **New** — 9 tests |
| `plugins/.../utils/shared/resourceUnits.ts` | **New** — K8s resource quantity parsers |
| `plugins/.../utils/shared/resourceUnits.test.ts` | **New** — 15 tests |
| `plugins/.../hooks/useDeployWizard.ts` | Added `quotaWarnings` state + useEffect |
| `plugins/.../components/DeployPure.tsx` | Render quota warning banner |
| `plugins/.../components/Deploy.tsx` | Pass `quotaWarnings` through |
| `plugins/.../DeployWizard.tsx` | Pass `quotaWarnings` through |

### PR DESCRIPTION
**Pull request by gambtho**
## Summary

The deploy wizard's server-side dry-run validates the Deployment object but not the pods the ReplicaSet controller creates. When a namespace has a ResourceQuota, users could deploy successfully only to find pods stuck in `FailedCreate` with no prior warning.

- Added `checkResourceQuota()` utility that fetches namespace ResourceQuotas and compares requested resources against remaining quota
- Shows a non-blocking warning banner in the Deploy review step when resources would exceed quota
- Added shared K8s resource quantity parsers (`parseCpuToMillicores`, `parseMemoryToBytes`, `formatCpu`, `formatMemory`)

## Type of Change

- [x] New feature (non-breaking change which adds functionality)

## Related Issues

Fixes #492 (quota warning portion; Map tab fix is in #493)

## Changes Made

| File | Change |
|------|--------|
| `utils/shared/resourceUnits.ts` | **New** — K8s resource quantity parsers and formatters |
| `utils/shared/resourceUnits.test.ts` | **New** — 15 unit tests |
| `DeployWizard/utils/quotaCheck.ts` | **New** — fetches namespace quotas, compares against deployment resources |
| `DeployWizard/utils/quotaCheck.test.ts` | **New** — 9 tests (fit, exceed, replicas, multi-container, RBAC fail-open, mixed docs) |
| `DeployWizard/hooks/useDeployWizard.ts` | Added `quotaWarnings` state + `useEffect` that runs quota check on Deploy step entry |
| `DeployWizard/components/DeployPure.tsx` | Renders quota warning banner (MUI `warning.main` color) |
| `DeployWizard/components/Deploy.tsx` | Passes `quotaWarnings` through |
| `DeployWizard/DeployWizard.tsx` | Passes `quotaWarnings` through |

### Design decisions

- **Warning, not a hard block** — users can still deploy even when quota would be exceeded (the quota may change, or they may know what they're doing)
- **Fail-open** — if the ResourceQuota fetch fails (e.g. RBAC), no warnings are shown rather than blocking deployment
- **Runs on step entry** — quota check runs via `useEffect` when entering the Deploy review step, so warnings appear before the user clicks Deploy
- **Replica-aware** — multiplies per-pod resources by `spec.replicas` (uses declared replicas, not HPA max, to keep it simple)
- **Checks 4 resource keys** — `requests.cpu`, `requests.memory`, `limits.cpu`, `limits.memory`

## Testing

- [x] Unit tests pass — 24 new tests all passing
- [x] TypeScript type check passes
- [x] ESLint passes (0 warnings)
- [x] Prettier formatting passes

### Test Cases

1. No quota in namespace — no warnings
2. Resources fit within quota — no warnings
3. Memory request exceeds remaining — warning with specific numbers
4. CPU exceeds remaining — warning returned
5. Replicas multiplied correctly (128Mi × 3 = 384Mi > 256Mi quota)
6. Multiple containers summed correctly
7. Non-Deployment resources (Service, ConfigMap) skipped
8. Fetch failure (RBAC) — returns empty array (fail-open)
9. Mixed docs — only Deployment checked

## Checklist

- [x] My code follows the project's style guidelines
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: plugins/aks-desktop/src/components/DeployWizard/components/DeployPure.tsx [hunk 1]
```diff
@@ -65,6 +69,43 @@ export default function DeployPure({
...
+          role="status"
+          sx={{
+            mb: 1,
+            p: 1.5,
+            border: '1px solid',
+            borderColor: 'warning.main',
+            borderRadius: 1,
+            color: 'text.primary',
+            backgroundColor: theme =>
+              theme.palette.mode === 'dark' ? 'rgba(237, 108, 2, 0.12)' : 'rgba(237, 108, 2, 0.08)',
```
Comment (sniok) [inline plugins/aks-desktop/src/components/DeployWizard/components/DeployPure.tsx]: we should be using theme colors instead of hardcoded colors that can look off for different themes
like theme.palette.warning.main

File: plugins/aks-desktop/src/components/DeployWizard/hooks/useDeployWizard.ts [hunk 2]
```diff
@@ -170,10 +218,43 @@ export function useDeployWizard({
...
+      .then(warnings => {
+        if (!cancelled) setQuotaWarnings(warnings);
+      })
+      .catch(() => {
+        if (!cancelled) setQuotaWarnings([]);
+      });
+    return () => {
+      cancelled = true;
+    };
+    // eslint-disable-next-line react-hooks/exhaustive-deps
```
Comment (sniok) [inline plugins/aks-desktop/src/components/DeployWizard/hooks/useDeployWizard.ts]: we don't have this rule enabled

File: plugins/aks-desktop/src/utils/shared/resourceUnits.ts [hunk 3]
```diff
@@ -0,0 +1,102 @@
...
+// Licensed under the Apache 2.0.
+
+/**
+ * Parses a Kubernetes CPU quantity string to millicores.
+ *
+ * @example parseCpuToMillicores("100m")  // 100
+ * @example parseCpuToMillicores("1")     // 1000
+ * @example parseCpuToMillicores("0.5")   // 500
+ */
+export function parseCpuToMillicores(val: string): number {
```
Comment (sniok) [inline plugins/aks-desktop/src/utils/shared/resourceUnits.ts:20]: we have similar units handling in headlamp https://github.com/kubernetes-sigs/headlamp/blob/main/frontend/src/lib/units.ts
could you check if that can be reused here?
